name: cheber_terminal
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_pty: ^0.4.0
  # macos_window_utils: ^1.1.3
  get_it: ^7.6.0
  super_drag_and_drop: ^0.4.0
  # xterm: ^3.5.0
  xterm:
    path: "../test/xterm.dart"
  rxdart: ^0.27.7
  yaml: ^3.1.2
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "lib/assets/app_icon/app_icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: TablerIcons
      fonts:
        - asset: lib/assets/fonts/tabler-icons.woff2
  assets:
    - lib/assets/
    - lib/modules/theme/themes/
